name: Terraform Apply for Deactivating Old Revisions

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var="tenant_id=b41b72d0-4e9f-4c26-8a69-f949f367c91d" \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}
